- docs/release_runbook.md
Adding a release runbook related to the `trigger_prerelease` workflow.
> release runbook

- .github/workflows/trigger_prerelease.yaml
This is useful to avoid this kind of message in slack:
> triggerPreRelease: without the title the slack message is malformed

- .github/workflows/trigger_prerelease.yaml
This PR includes two changes to extend trigger_prerelease reusable workflow:
- It adds support to excluded/included fields of the [release-toolkit/contrib/ohi-release-notes action](https://github.com/newrelic/release-toolkit/tree/main/contrib/ohi-release-notes).
- It fixes the failure message: it includes the repository name from the event and adds a link to the action-run where the job failed.
> NR-101030: trigger prerelease updates

- README.md
- renovate-base.json5
ℹ️ This includes a base renovate configuration for CoreInt repositories.
🗒️  It can be used directly like this:
```json5
{
"extends": [
"github>newrelic/coreint-automation:renovate-base.json5"
]
}
```
Or include additional rules if needed:
```json5
"extends": [
"github>newrelic/coreint-automation:renovate-base.json5"
],
"packageRules": [
// ...
]
```
🧪 It has been tested in [this nri-postgresql fork](https://github.com/sigilioso/nri-postgresql) using a [temp tag](https://github.com/newrelic/coreint-automation/releases/tag/temp) to be removed once the PR is merged. The corresponding [renovate dashboard issue](https://github.com/sigilioso/nri-postgresql/issues/3) shows that rules are being applied as expected.
> NR-122258: include renovate base config

- terraform_modules/base_framework/common-network.tf
- terraform_modules/base_framework/tls-ca-and-ssh-keys.tf
- terraform_modules/canary_template/resource.tf
* Updates common network to include a SG that allows traffic between resources in the vpc (This is implemented to workaround communication between EKS pods and internal resources)
* Outputs the SSSh key name to be easily imported by new resources
* Updates template example
> update sg/ssh key and example template (NR-114593)

- .github/workflows/trigger_prerelease.yaml
In order for the K8s Agent Team to use their own GitHub bot to sign commits, we need to parameterize the name and email values to be used
> Parameterize GitHub bot as reusable workflow input

- .github/workflows/block.yaml
- .github/workflows/repolinter.yml
- .github/workflows/reposettings.yaml
- .github/workflows/trigger_prerelease.yaml
- .github/workflows/unblock.yaml
I misread the PRs from renovate and merged PRs that changed the tag to a commit hash.
We don't know if renovate will update commits written like that and if renovate might stick to master instead of following tag conventions.
As this is an untested territory I prefer to revert the change and keep working with tags.
> Revert actions using hash instead of tag

- .github/workflows/on_push_pr.yaml
- .github/workflows/repolinter.yml
- .github/workflows/reusable_repolinter.yaml
- .github/workflows/reusable_security.yaml
- .github/workflows/reusable_trigger_prerelease.yaml
- .github/workflows/security.yaml
- renovate-base.json5
- renovate.json
As the first iteration to standardize the pipelines, I need all the pipelines to be named the same way
I'll need to run scripts to analyze them such as `diff` and `yq` to see the differences between them and having them with different names makes the scripts a mess.
This is the bare minimum start even if the effort to standardize the pipelines finally does not happen.
This PR also renames the reusable pipelines with the prefix `reusable_` so we can have more readable pipelines as this repository is expected to grow a lot in the near future.
> [chore] Rename pipelines and centralise the security ones

- .github/workflows/reusable_repolinter.yaml
It seems that at least one repo was using the community project header instead of the community plus one.
When I copied and pasted this pipeline, I did not realize it so now Repolinter issues are popping up on all repositories.
This should fix future issues and fixes:
* newrelic/nri-rabbitmq#139
* newrelic/nri-couchbase#91
* newrelic/nri-consul#94
* newrelic/nri-nginx#137
* newrelic/nri-cassandra#173
> Wrong manifest on repolinter workflow

- .github/workflows/_static_analysis.yaml
- .github/workflows/_test_build_fake_prerelease.yaml
- .github/workflows/_test_build_nix.yaml
- .github/workflows/_test_integration_nix.yaml
- .github/workflows/_test_nix.yaml
- .github/workflows/_test_windows.yaml
- .github/workflows/reusable_push_pr.yaml
- README.md
This PR adds a Push PR reusable workflows composed of several other pluggable single workflows.
These workflows have been tested in the following PRs:
- https://github.com/newrelic/nri-redis/pull/182
- https://github.com/newrelic/nri-apache/pull/114
- https://github.com/newrelic/nri-oracledb/pull/155
**Note:** To test the fake prereleases flow (such as the 2nd PR) I've used a `worflow_run` approach in order to run the `Test Build Windows` workflow once the previous needed `Test Build Nix fake prerelease` workflows is completed. From GitHub notes, we are not going to be able to test this until this **workflow is merged in the default branch.**
More details here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> Note: This event will only trigger …
> NR-211968: Add push pr reusable workflows

- .github/workflows/_static_analysis.yaml
We need to reintroduce the `continue-on-error` flag with the condition `github.event_name != 'pull_request'` to prevent workflow failures when merging changes into the master branch, such as the one encountered in this [example](https://github.com/newrelic/nri-redis/actions/runs/7740601084/job/21105883286).
The reason for this is that golangci-lint behaves differently when run in different contexts:
1. When run in a merge  context:
- In this mode, golangci-lint performs linting on the entire codebase without taking into account the changes being merged.
- Example command: `/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint run --out-format=github-actions`
2. When run from a pull request (PR) context:
- In this mode, golangci-lint analyzes and lints only the changes made in the …
> Fix linting errors

- .github/workflows/_test_build_fake_prerelease.yaml
- .github/workflows/reusable_push_pr.yaml
This PR introduces to new fields in the `reusable_push_pr` workflow:
- `fake_prerelease_goarch_matrix`
- `fake_prerelease_download_nrjmx` 
These fields are needed in nrjmx based integrations. 
Tested in nri-cassandra: newrelic/nri-cassandra#181
- Move `v2` tag after merging it.
> [reusable workflows] required fake-prerelease fields for nrjmx based integrations

- .github/workflows/reusable_pre_release.yaml
Introduce the parameters required for nrjmx based integrations in the reusable pre-release workflow (in the same way it was done for push/pr fake-prerelease #51)
> feat: update pre-relase reusable workflow to support nrjmx based integrations

- tools/common-functions.sh
- tools/list-failed-releases.sh
- tools/list-not-released-prereleases.sh
I have added two scripts that allows us to see which prereleases have not been released yet and which releases have a failed to release properly.
After [the comment that @sigilioso left](https://github.com/newrelic/coreint-automation/pull/59#discussion_r1549071739), I moved the constants and the logic to see if a commit has all check runs consistently finished to a common file.
While testing the scripts, I suffered reading the output problems, so I changed it a bit. Now running the scripts should look like this:
`./tools/list-not-released-prereleases.sh`
```
>>>  Prerelease found for nri-kafka: https://github.com/newrelic/nri-kafka/releases/tag/v3.7.2
You can release it by running: `gh release edit -R "newrelic/nri-kafka" "v3.7.2" --prerelease=false --latest'
>>>  Prerelease found for …
```
> Add helper scripts for hero duties (NR-249369)

- .github/workflows/reusable_pre_release.yaml
- .github/workflows/reusable_trigger_prerelease.yaml
This PR edits pre-release titles to reflect the corresponding artifacts states:
| State | Title | pre-release |
| - | - | - |
| pre-release created | `vX.Y.Z (artifacts-pending)` | `true` |
| pre-release ready | `vX.Y.Z` | `true` |
| pre-release failure| `vX.Y.Z (pre-release-failure)` | `true` |
This should help us to easily identify failing pre-releases both manually and automatically.
Since releases are not promoted automatically (yet), the release workflow is not modified. The release title should also reflect failures when promoting from pre-releases to releases automatically.
> NR-249371: reflect failures in pre-release title

- tools/list-not-released-prereleases.sh
Updates the script to list not-released prereleased after changes in #60
> chore: update script to list not-prereleased-releaases

- .github/workflows/reusable_release_automation.yaml
- tools/list-not-released-prereleases.sh
This PR introduces a new reusable workflow, `reusable_promote_prerelease.yaml`, designed to automate the promotion of validated prereleases to full releases. It streamlines our release process by ensuring only prereleases without `"artifacts-pending"` or `"pre-release-failure"` labels are promoted.
I also added the capability of blocking the process by leveraging the block endpoint check.
> NR-249372: Promote prereleases to releases

- .github/workflows/reusable_release_automation.yaml
The reusable prerelease is already used on repositories that have images on a different path or required release toolkit to monitor different files.
The two examples:
* https://github.com/newrelic/infrastructure-bundle/blob/043dbe88990731586bcadc0bea94a00345e9cc41/.github/workflows/trigger_prerelease.yml#L15-L16
* https://github.com/newrelic/nri-ecs/blob/257396a02af6f4bd373415d77ef988994a9dd2e3/.github/workflows/trigger_prerelease.yml#L19-L20
This keeps the defaults as it is and should cover most of the OHIs but open the possibility to reuse this pipeline with more repositories.
> Allow reusable release to be used with image repos

- .github/workflows/reusable_release_automation.yaml
We have pipelines failing with this error:
```
The workflow is not valid. newrelic/coreint-automation/.github/workflows/reusable_release_automation.yaml@v3 (Line: 123, Col: 22): Invalid input, excluded-dirs is not defined in the referenced workflow. newrelic/coreint-automation/.github/workflows/reusable_release_automation.yaml@v3 (Line: 124, Col: 23): Invalid input, excluded-files is not defined in the referenced workflow.
```
Like here: https://github.com/newrelic/nri-ecs/actions/runs/8740290131
Note: on the run above, the first run failed because I forgot to move the `v3` tag, is the second run the one failing with the issue this PR fixes.
The this was a copy and paste leftover as I copy the inputs from the pre-release pipeline instead of the trigger prerelease where the inputs are …
> Fix invalid input

- .github/workflows/reusable_release_automation.yaml
This fixes https://github.com/newrelic/nri-haproxy/actions/runs/8793791827 in a clean way.
> Skip promotion when no prerelease

- tools/common-functions.sh
- tools/list-open-prs.sh
I know that there is a panel in GitHub for open PRs but not only I would have to add filters to filter Draft PRs but also to filter all repos that are open source that I am subscribed (like OTel or personal projects)
To reduce the amount of noise and have a way better view, this script should do the trick.
Example of output:
```
⚠️ The repository nri-mysql has has unmerged PRs that are not marked as draft:
#156  chore(deps): update golang version to v1.22.6(app/renovate)  https://github.com/newrelic/nri-mysql/pull/156
⚠️ The repository nri-cassandra has has unmerged PRs that are not marked as draft:
#202  chore(deps): update golang version to v1.22.6(app/renovate)    https://github.com/newrelic/nri-cassandra/pull/202
#147  fix(deps): update module gopkg.in/yaml.v2 to v3(app/renovate) …
```
> Add tool to list open PRs

- .github/workflows/reusable_pre_release.yaml
Add a new optional input parameter to the reusable prerelase workflow with a default value of `infrastructure_agent/`
Allows OHIs to specify a different path for testing the package creation and uploads without impacting the staging s3. The installation test will still use the default path, which should be changed as part of [NR-340027](https://new-relic.atlassian.net/browse/NR-340027)
[NR-340027]: https://new-relic.atlassian.net/browse/NR-340027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add dest_prefix input parameter

- renovate-base.json5
Changes in this PR: 
- Separated go, golang package updates (from all patch, minor updates rule)
- Grouped go, golang package with **minor**, **major** versions under a single group name - `golang version`
- Grouped go, golang package with **patch** versions with name - `golang patch version`
- Enabled version bump with group name - `golang version` but disabled automerge
- Enabled both version bump and automerge for `golang patch version` group
Steps that I went through to test the auto-merge works as expected
TestCase-1: If there is a new GoLang Patch version released the renovate bot should auto-merge the PR.
1. Created a fork of the nri-mysql repo
2. Copied the config from `coreint-automation/renovate-base.json5` and added it to forked `nri-mysql/.github/renovate.json5`
3. Updated the …
> Upgrade Golang versions automatically when new patch version is released

- .github/workflows/reusable_on_release.yaml
- .github/workflows/reusable_pre_release.yaml
This is in addition to https://github.com/newrelic/infrastructure-publish-action/pull/163 and https://github.com/newrelic/nri-redis/pull/208
> add publish to s3 fips task

- renovate.json
Changes in this PR
Configured renovate.json to update the patch versions for each version in the list `go-version` present in `build_publish_builder_image.yaml` file.
Tested the above by creating a fork of this repo and renovate has created [PR1](https://github.com/sairaj18/coreint-automation-test/pull/9), [PR2](https://github.com/sairaj18/coreint-automation-test/pull/7) (It has created PR1 with automerge true But, I merged the PR1 manually in-order to see if the PR2 gets raised)
> NR-340296 Update renovate config to update golang version for Dockerfile ARG

- .github/workflows/reusable_pre_release.yaml
- test-fips-action/action.yml
Add fips-test action that checks all the binaries in a given folder. It checks subfolders with name: `*-fips*` and any binary inside those folders should be fips compiled.
https://github.com/newrelic/nri-redis/actions/runs/12273589913/job/34244742644
> add fips test action in step in reusable prerelease

- tools/common-functions.sh
- tools/list-not-released-prereleases.sh
The `list-not-released-prereleases.sh` script was failing due to a deprecated team id. This PR updates it and also skips repositories not publishing releases.
> fix: update tools team-id

- build/Dockerfile
- build/sign.sh
- build/sign_deb.exp
- build/sign_rpm.exp
- build/sign_tar.exp
Modify signing packages to SHA-256 and move the signing files from integrations to automations repo.
> ci: move signing packages to automation page

- .github/workflows/reusable_image_release.yaml
Testing the docker image releases one by one.
Can be merged once thats done.
> Nr 341876 make docker images pre release uniform

- .github/workflows/reusable_nightly.yaml
The slack channel that reusable nightly workflow points to is incorrect.
Now points to `secrets.COREINT_SLACK_CHANNEL`
> Reusable nightly workflow points to the right channel

- .github/workflows/reusable_image_release.yaml
- .github/workflows/reusable_nightly.yaml
The notify steps in both the reusable nightly and reusable image release workflows were failing because `COREINT_SLACK_TOKEN` and `COREINT_SLACK_CHANNEL` were not being passed as secrets.
They are now required to be passed to these workflows.
> Added slack token and channel to workflow secrets

- .github/workflows/_static_analysis.yaml
Latest version of golang-lint breaks our CI. So, fixing it to v1.63. We need to identify and fix it soon. Created https://new-relic.atlassian.net/browse/NR-368969 to fix this.
> Fix: golangci lint breaks with v1.64.2

- build/Dockerfile
[nri-prometheus](https://github.com/newrelic/nri-prometheus) uses `buildx` to create images using `goreleaser`. Therefore, adding these in the centralized builder image.
<details>
<summary>Building Image</summary>
```log
❯ docker build -f build/Dockerfile --platform=linux/amd64 -t fips-test-img .
[+] Building 30.6s (12/12) FINISHED                           docker:desktop-linux
=> [internal] load build definition from Dockerfile                          0.0s
=> => transferring dockerfile: 2.21kB                                        0.0s
=> [internal] load metadata for docker.io/library/ubuntu:16.04               1.1s
=> [internal] load .dockerignore                                             0.0s
=> => transferring context: 2B                                               0.0s
=> [1/8] …
```
> add docker and buildx to the builder image

- .github/workflows/reusable_release_automation.yaml
Assumption: The reusable release automation [workflow](https://github.com/newrelic/coreint-automation/blob/6402d3e2f638fc7781744f85ca97686b655ae73b/.github/workflows/reusable_release_automation.yaml#L83) has to fetch the latest pre-release that is available after the last release.
Existing Logic of the reusable release automation workflow 
1. Fetches the list of releases in desc order of the publishedAt date-time
2. Filters the list to get pre-releases that are created after the last release
3. Sort the pre-releases by the publishedAt time and get the first value in the filtered results.
Changes In the PR - removed the sorting of pre-releases as it is re-ordering the results from descending to ascending and the final result is the 1st pre-release that has been created after the last …
> fix: remove sorting of results after fetching releases in desc order

- .github/workflows/_static_analysis.yaml
- .golangci.yml
Add `.golangci.yml` to this repo and leverage it when running `golangci-lint-action@v8`
> refactor: make golangci.yml reusable

- .github/workflows/reusable_on_release.yaml
- .github/workflows/reusable_pre_release.yaml
The standard github runner is running out of disk space while publishing packages to S3.
Upgrading to the 4 core linux runner.
> Upgraded runner used for publishing

- .github/workflows/daily_releases.yml
Our daily release status messages in Slack are pretty broken right now. This makes it tough to quickly see what's going on with releases.
This fixes the formatting by switching to proper Slack markup, turning those ugly tables into clean bullet points, and adding some nice emojis to make things easier to scan. Also got rid of that annoying workflow link at the bottom that nobody needs.
Now the team will actually get readable daily updates showing whether releases are blocked, what's scheduled for today, and which pre-releases are ready to go - all in a format that doesn't hurt your eyes.
> feat: daily slack notification for automatic release
